-- category
INSERT INTO category (name, icon) VALUES ('sport', '⚽️' );
INSERT INTO category (name, icon) VALUES ('people', '👫' );
INSERT INTO category (name, icon) VALUES ('world', '🌍' );
INSERT INTO category (name, icon) VALUES ('objects', '🛠️' );
INSERT INTO category (name, icon) VALUES ('random', '🎲' );
INSERT INTO category (name, icon) VALUES ('actions', '🕺' );
INSERT INTO category (name, icon) VALUES ('nature', '🌊' );

--word
INSERT INTO word (word) VALUES ('Soccer');
INSERT INTO word (word) VALUES ('Basketball');
INSERT INTO word (word) VALUES ('Baseball');
INSERT INTO word (word) VALUES ('American Football');
INSERT INTO word (word) VALUES ('Tennis');
INSERT INTO word (word) VALUES ('Golf');
INSERT INTO word (word) VALUES ('Rugby');
INSERT INTO word (word) VALUES ('Cricket');
INSERT INTO word (word) VALUES ('Ice Hockey');
INSERT INTO word (word) VALUES ('Field Hockey');
INSERT INTO word (word) VALUES ('Volleyball');
INSERT INTO word (word) VALUES ('Table Tennis');
INSERT INTO word (word) VALUES ('Badminton');
INSERT INTO word (word) VALUES ('Swimming');
INSERT INTO word (word) VALUES ('Track and Field');
INSERT INTO word (word) VALUES ('Boxing');
INSERT INTO word (word) VALUES ('Mixed Martial Arts (MMA)');
INSERT INTO word (word) VALUES ('Wrestling');
INSERT INTO word (word) VALUES ('Gymnastics');
INSERT INTO word (word) VALUES ('Cycling');
INSERT INTO word (word) VALUES ('Skiing');
INSERT INTO word (word) VALUES ('Snowboarding');
INSERT INTO word (word) VALUES ('Surfing');
INSERT INTO word (word) VALUES ('Skateboarding');
INSERT INTO word (word) VALUES ('Sailing');
INSERT INTO word (word) VALUES ('Rowing');
INSERT INTO word (word) VALUES ('Archery');
INSERT INTO word (word) VALUES ('Fencing');
INSERT INTO word (word) VALUES ('Equestrian');
INSERT INTO word (word) VALUES ('Lacrosse');
INSERT INTO word (word) VALUES ('Handball');
INSERT INTO word (word) VALUES ('Softball');
INSERT INTO word (word) VALUES ('Water Polo');
INSERT INTO word (word) VALUES ('Biathlon');
INSERT INTO word (word) VALUES ('Triathlon');
INSERT INTO word (word) VALUES ('Weightlifting');
INSERT INTO word (word) VALUES ('Powerlifting');
INSERT INTO word (word) VALUES ('Bodybuilding');
INSERT INTO word (word) VALUES ('Curling');
INSERT INTO word (word) VALUES ('Darts');
INSERT INTO word (word) VALUES ('Bowling');
INSERT INTO word (word) VALUES ('Snooker');
INSERT INTO word (word) VALUES ('Horse Racing');
INSERT INTO word (word) VALUES ('Auto Racing (NASCAR, Formula 1)');
INSERT INTO word (word) VALUES ('Motocross');
INSERT INTO word (word) VALUES ('Bobsleigh');
INSERT INTO word (word) VALUES ('Luge');
INSERT INTO word (word) VALUES ('Skeleton');
INSERT INTO word (word) VALUES ('Judo');
INSERT INTO word (word) VALUES ('Taekwondo');
INSERT INTO word (word) VALUES ('Manchester United');
INSERT INTO word (word) VALUES ('Real Madrid');
INSERT INTO word (word) VALUES ('FC Barcelona');
INSERT INTO word (word) VALUES ('Bayern Munich');
INSERT INTO word (word) VALUES ('Liverpool FC');
INSERT INTO word (word) VALUES ('New England Patriots');
INSERT INTO word (word) VALUES ('Green Bay Packers');
INSERT INTO word (word) VALUES ('Los Angeles Lakers');
INSERT INTO word (word) VALUES ('Golden State Warriors');
INSERT INTO word (word) VALUES ('Chicago Bulls');
INSERT INTO word (word) VALUES ('New York Yankees');
INSERT INTO word (word) VALUES ('Boston Red Sox');
INSERT INTO word (word) VALUES ('Los Angeles Dodgers');
INSERT INTO word (word) VALUES ('Toronto Maple Leafs');
INSERT INTO word (word) VALUES ('Montreal Canadiens');
INSERT INTO word (word) VALUES ('Chicago Blackhawks');
INSERT INTO word (word) VALUES ('Mumbai Indians');
INSERT INTO word (word) VALUES ('Chennai Super Kings');
INSERT INTO word (word) VALUES ('Sydney Sixers');
INSERT INTO word (word) VALUES ('Leinster Rugby');
INSERT INTO word (word) VALUES ('New Zealand All Blacks');
INSERT INTO word (word) VALUES ('Toulouse');
INSERT INTO word (word) VALUES ('Paris Saint-Germain');
INSERT INTO word (word) VALUES ('Juventus');
INSERT INTO word (word) VALUES ('AC Milan');
INSERT INTO word (word) VALUES ('San Francisco 49ers');
INSERT INTO word (word) VALUES ('Dallas Cowboys');
INSERT INTO word (word) VALUES ('Boston Celtics');
INSERT INTO word (word) VALUES ('Houston Rockets');
INSERT INTO word (word) VALUES ('Atlanta Braves');
INSERT INTO word (word) VALUES ('Philadelphia Flyers');
INSERT INTO word (word) VALUES ('Pittsburgh Penguins');
INSERT INTO word (word) VALUES ('Kolkata Knight Riders');
INSERT INTO word (word) VALUES ('Brisbane Heat');
INSERT INTO word (word) VALUES ('Bath Rugby');
INSERT INTO word (word) VALUES ('Saracens');
INSERT INTO word (word) VALUES ('Atletico Madrid');
INSERT INTO word (word) VALUES ('Borussia Dortmund');
INSERT INTO word (word) VALUES ('Inter Milan');
INSERT INTO word (word) VALUES ('Cleveland Browns');
INSERT INTO word (word) VALUES ('Miami Dolphins');
INSERT INTO word (word) VALUES ('Milwaukee Bucks');
INSERT INTO word (word) VALUES ('Phoenix Suns');
INSERT INTO word (word) VALUES ('St. Louis Cardinals');
INSERT INTO word (word) VALUES ('New York Mets');
INSERT INTO word (word) VALUES ('Edmonton Oilers');
INSERT INTO word (word) VALUES ('Detroit Red Wings');
INSERT INTO word (word) VALUES ('Rajasthan Royals');
INSERT INTO word (word) VALUES ('Delhi Capitals');
INSERT INTO word (word) VALUES ('Northampton Saints');
INSERT INTO word (word) VALUES ('Lionel Messi');
INSERT INTO word (word) VALUES ('Cristiano Ronaldo');
INSERT INTO word (word) VALUES ('LeBron James');
INSERT INTO word (word) VALUES ('Michael Jordan');
INSERT INTO word (word) VALUES ('Serena Williams');
INSERT INTO word (word) VALUES ('Roger Federer');
INSERT INTO word (word) VALUES ('Tiger Woods');
INSERT INTO word (word) VALUES ('Tom Brady');
INSERT INTO word (word) VALUES ('Usain Bolt');
INSERT INTO word (word) VALUES ('Muhammad Ali');
INSERT INTO word (word) VALUES ('Mike Tyson');
INSERT INTO word (word) VALUES ('Conor McGregor');
INSERT INTO word (word) VALUES ('Ronda Rousey');
INSERT INTO word (word) VALUES ('Simone Biles');
INSERT INTO word (word) VALUES ('Michael Phelps');
INSERT INTO word (word) VALUES ('Katie Ledecky');
INSERT INTO word (word) VALUES ('Rafael Nadal');
INSERT INTO word (word) VALUES ('Novak Djokovic');
INSERT INTO word (word) VALUES ('Kobe Bryant');
INSERT INTO word (word) VALUES ('Shaquille O''Neal');
INSERT INTO word (word) VALUES ('Sachin Tendulkar');
INSERT INTO word (word) VALUES ('Virat Kohli');
INSERT INTO word (word) VALUES ('Steve Smith');
INSERT INTO word (word) VALUES ('Pelé');
INSERT INTO word (word) VALUES ('Diego Maradona');
INSERT INTO word (word) VALUES ('Neymar Jr.');
INSERT INTO word (word) VALUES ('David Beckham');
INSERT INTO word (word) VALUES ('Eliud Kipchoge');
INSERT INTO word (word) VALUES ('Mo Farah');
INSERT INTO word (word) VALUES ('Lewis Hamilton');
INSERT INTO word (word) VALUES ('Ayrton Senna');
INSERT INTO word (word) VALUES ('Valentino Rossi');
INSERT INTO word (word) VALUES ('Danica Patrick');
INSERT INTO word (word) VALUES ('Nadia Comăneci');
INSERT INTO word (word) VALUES ('Yelena Isinbayeva');
INSERT INTO word (word) VALUES ('Carl Lewis');
INSERT INTO word (word) VALUES ('Jesse Owens');
INSERT INTO word (word) VALUES ('Jackie Joyner-Kersee');
INSERT INTO word (word) VALUES ('Lance Armstrong');
INSERT INTO word (word) VALUES ('Chris Froome');
INSERT INTO word (word) VALUES ('Eddie Hall');
INSERT INTO word (word) VALUES ('Hafþór Júlíus Björnsson');
INSERT INTO word (word) VALUES ('Magnus Carlsen');
INSERT INTO word (word) VALUES ('Garry Kasparov');
INSERT INTO word (word) VALUES ('John Cena');
INSERT INTO word (word) VALUES ('Dwayne ''The Rock'' Johnson');
INSERT INTO word (word) VALUES ('Andre Agassi');
INSERT INTO word (word) VALUES ('Pete Sampras');
INSERT INTO word (word) VALUES ('Martina Navratilova');
INSERT INTO word (word) VALUES ('Steffi Graf');

--word_category
INSERT INTO word_category (word_id, category_id) VALUES (1, 1);
INSERT INTO word_category (word_id, category_id) VALUES (2, 1);
INSERT INTO word_category (word_id, category_id) VALUES (3, 1);
INSERT INTO word_category (word_id, category_id) VALUES (4, 1);
INSERT INTO word_category (word_id, category_id) VALUES (5, 1);
INSERT INTO word_category (word_id, category_id) VALUES (6, 1);
INSERT INTO word_category (word_id, category_id) VALUES (7, 1);
INSERT INTO word_category (word_id, category_id) VALUES (8, 1);
INSERT INTO word_category (word_id, category_id) VALUES (9, 1);
INSERT INTO word_category (word_id, category_id) VALUES (10, 1);
INSERT INTO word_category (word_id, category_id) VALUES (11, 1);
INSERT INTO word_category (word_id, category_id) VALUES (12, 1);
INSERT INTO word_category (word_id, category_id) VALUES (13, 1);
INSERT INTO word_category (word_id, category_id) VALUES (14, 1);
INSERT INTO word_category (word_id, category_id) VALUES (15, 1);
INSERT INTO word_category (word_id, category_id) VALUES (16, 1);
INSERT INTO word_category (word_id, category_id) VALUES (17, 1);
INSERT INTO word_category (word_id, category_id) VALUES (18, 1);
INSERT INTO word_category (word_id, category_id) VALUES (19, 1);
INSERT INTO word_category (word_id, category_id) VALUES (20, 1);
INSERT INTO word_category (word_id, category_id) VALUES (21, 1);
INSERT INTO word_category (word_id, category_id) VALUES (22, 1);
INSERT INTO word_category (word_id, category_id) VALUES (23, 1);
INSERT INTO word_category (word_id, category_id) VALUES (24, 1);
INSERT INTO word_category (word_id, category_id) VALUES (25, 1);
INSERT INTO word_category (word_id, category_id) VALUES (26, 1);
INSERT INTO word_category (word_id, category_id) VALUES (27, 1);
INSERT INTO word_category (word_id, category_id) VALUES (28, 1);
INSERT INTO word_category (word_id, category_id) VALUES (29, 1);
INSERT INTO word_category (word_id, category_id) VALUES (30, 1);
INSERT INTO word_category (word_id, category_id) VALUES (31, 1);
INSERT INTO word_category (word_id, category_id) VALUES (32, 1);
INSERT INTO word_category (word_id, category_id) VALUES (33, 1);
INSERT INTO word_category (word_id, category_id) VALUES (34, 1);
INSERT INTO word_category (word_id, category_id) VALUES (35, 1);
INSERT INTO word_category (word_id, category_id) VALUES (36, 1);
INSERT INTO word_category (word_id, category_id) VALUES (37, 1);
INSERT INTO word_category (word_id, category_id) VALUES (38, 1);
INSERT INTO word_category (word_id, category_id) VALUES (39, 1);
INSERT INTO word_category (word_id, category_id) VALUES (40, 1);
INSERT INTO word_category (word_id, category_id) VALUES (41, 1);
INSERT INTO word_category (word_id, category_id) VALUES (42, 1);
INSERT INTO word_category (word_id, category_id) VALUES (43, 1);
INSERT INTO word_category (word_id, category_id) VALUES (44, 1);
INSERT INTO word_category (word_id, category_id) VALUES (45, 1);
INSERT INTO word_category (word_id, category_id) VALUES (46, 1);
INSERT INTO word_category (word_id, category_id) VALUES (47, 1);
INSERT INTO word_category (word_id, category_id) VALUES (48, 1);
INSERT INTO word_category (word_id, category_id) VALUES (49, 1);
INSERT INTO word_category (word_id, category_id) VALUES (50, 1);
INSERT INTO word_category (word_id, category_id) VALUES (51, 1);
INSERT INTO word_category (word_id, category_id) VALUES (52, 1);
INSERT INTO word_category (word_id, category_id) VALUES (53, 1);
INSERT INTO word_category (word_id, category_id) VALUES (54, 1);
INSERT INTO word_category (word_id, category_id) VALUES (55, 1);
INSERT INTO word_category (word_id, category_id) VALUES (56, 1);
INSERT INTO word_category (word_id, category_id) VALUES (57, 1);
INSERT INTO word_category (word_id, category_id) VALUES (58, 1);
INSERT INTO word_category (word_id, category_id) VALUES (59, 1);
INSERT INTO word_category (word_id, category_id) VALUES (60, 1);
INSERT INTO word_category (word_id, category_id) VALUES (61, 1);
INSERT INTO word_category (word_id, category_id) VALUES (62, 1);
INSERT INTO word_category (word_id, category_id) VALUES (63, 1);
INSERT INTO word_category (word_id, category_id) VALUES (64, 1);
INSERT INTO word_category (word_id, category_id) VALUES (65, 1);
INSERT INTO word_category (word_id, category_id) VALUES (66, 1);
INSERT INTO word_category (word_id, category_id) VALUES (67, 1);
INSERT INTO word_category (word_id, category_id) VALUES (68, 1);
INSERT INTO word_category (word_id, category_id) VALUES (69, 1);
INSERT INTO word_category (word_id, category_id) VALUES (70, 1);
INSERT INTO word_category (word_id, category_id) VALUES (71, 1);
INSERT INTO word_category (word_id, category_id) VALUES (72, 1);
INSERT INTO word_category (word_id, category_id) VALUES (73, 1);
INSERT INTO word_category (word_id, category_id) VALUES (74, 1);
INSERT INTO word_category (word_id, category_id) VALUES (75, 1);
INSERT INTO word_category (word_id, category_id) VALUES (76, 1);
INSERT INTO word_category (word_id, category_id) VALUES (77, 1);
INSERT INTO word_category (word_id, category_id) VALUES (78, 1);
INSERT INTO word_category (word_id, category_id) VALUES (79, 1);
INSERT INTO word_category (word_id, category_id) VALUES (80, 1);
INSERT INTO word_category (word_id, category_id) VALUES (81, 1);
INSERT INTO word_category (word_id, category_id) VALUES (82, 1);
INSERT INTO word_category (word_id, category_id) VALUES (83, 1);
INSERT INTO word_category (word_id, category_id) VALUES (84, 1);
INSERT INTO word_category (word_id, category_id) VALUES (85, 1);
INSERT INTO word_category (word_id, category_id) VALUES (86, 1);
INSERT INTO word_category (word_id, category_id) VALUES (87, 1);
INSERT INTO word_category (word_id, category_id) VALUES (88, 1);
INSERT INTO word_category (word_id, category_id) VALUES (89, 1);
INSERT INTO word_category (word_id, category_id) VALUES (90, 1);
INSERT INTO word_category (word_id, category_id) VALUES (91, 1);
INSERT INTO word_category (word_id, category_id) VALUES (92, 1);
INSERT INTO word_category (word_id, category_id) VALUES (93, 1);
INSERT INTO word_category (word_id, category_id) VALUES (94, 1);
INSERT INTO word_category (word_id, category_id) VALUES (95, 1);
INSERT INTO word_category (word_id, category_id) VALUES (96, 1);
INSERT INTO word_category (word_id, category_id) VALUES (97, 1);
INSERT INTO word_category (word_id, category_id) VALUES (98, 1);
INSERT INTO word_category (word_id, category_id) VALUES (99, 1);
INSERT INTO word_category (word_id, category_id) VALUES (100, 1);
INSERT INTO word_category (word_id, category_id) VALUES (101, 1);
INSERT INTO word_category (word_id, category_id) VALUES (102, 1);
INSERT INTO word_category (word_id, category_id) VALUES (103, 1);
INSERT INTO word_category (word_id, category_id) VALUES (104, 1);
INSERT INTO word_category (word_id, category_id) VALUES (105, 1);
INSERT INTO word_category (word_id, category_id) VALUES (106, 1);
INSERT INTO word_category (word_id, category_id) VALUES (107, 1);
INSERT INTO word_category (word_id, category_id) VALUES (108, 1);
INSERT INTO word_category (word_id, category_id) VALUES (109, 1);
INSERT INTO word_category (word_id, category_id) VALUES (110, 1);
INSERT INTO word_category (word_id, category_id) VALUES (111, 1);
INSERT INTO word_category (word_id, category_id) VALUES (112, 1);
INSERT INTO word_category (word_id, category_id) VALUES (113, 1);
INSERT INTO word_category (word_id, category_id) VALUES (114, 1);
INSERT INTO word_category (word_id, category_id) VALUES (115, 1);
INSERT INTO word_category (word_id, category_id) VALUES (116, 1);
INSERT INTO word_category (word_id, category_id) VALUES (117, 1);
INSERT INTO word_category (word_id, category_id) VALUES (118, 1);
INSERT INTO word_category (word_id, category_id) VALUES (119, 1);
INSERT INTO word_category (word_id, category_id) VALUES (120, 1);
INSERT INTO word_category (word_id, category_id) VALUES (121, 1);
INSERT INTO word_category (word_id, category_id) VALUES (122, 1);
INSERT INTO word_category (word_id, category_id) VALUES (123, 1);
INSERT INTO word_category (word_id, category_id) VALUES (124, 1);
INSERT INTO word_category (word_id, category_id) VALUES (125, 1);
INSERT INTO word_category (word_id, category_id) VALUES (126, 1);
INSERT INTO word_category (word_id, category_id) VALUES (127, 1);
INSERT INTO word_category (word_id, category_id) VALUES (128, 1);
INSERT INTO word_category (word_id, category_id) VALUES (129, 1);
INSERT INTO word_category (word_id, category_id) VALUES (130, 1);
INSERT INTO word_category (word_id, category_id) VALUES (131, 1);
INSERT INTO word_category (word_id, category_id) VALUES (132, 1);
INSERT INTO word_category (word_id, category_id) VALUES (133, 1);
INSERT INTO word_category (word_id, category_id) VALUES (134, 1);
INSERT INTO word_category (word_id, category_id) VALUES (135, 1);
INSERT INTO word_category (word_id, category_id) VALUES (136, 1);
INSERT INTO word_category (word_id, category_id) VALUES (137, 1);
INSERT INTO word_category (word_id, category_id) VALUES (138, 1);
INSERT INTO word_category (word_id, category_id) VALUES (139, 1);
INSERT INTO word_category (word_id, category_id) VALUES (140, 1);
INSERT INTO word_category (word_id, category_id) VALUES (141, 1);
INSERT INTO word_category (word_id, category_id) VALUES (142, 1);
INSERT INTO word_category (word_id, category_id) VALUES (143, 1);
INSERT INTO word_category (word_id, category_id) VALUES (144, 1);
INSERT INTO word_category (word_id, category_id) VALUES (145, 1);
INSERT INTO word_category (word_id, category_id) VALUES (146, 1);
INSERT INTO word_category (word_id, category_id) VALUES (147, 1);
INSERT INTO word_category (word_id, category_id) VALUES (148, 1);
INSERT INTO word_category (word_id, category_id) VALUES (149, 1);
INSERT INTO word_category (word_id, category_id) VALUES (150, 1);

