export const categories = [
  { name: "sport", icon: "⚽️" },
  { name: "people", icon: "👫" },
  { name: "world", icon: "🌍" },
  { name: "objects", icon: "🛠️" },
  { name: "random", icon: "🎲" },
  { name: "actions", icon: "🕺" },
  { name: "nature", icon: "🌊" },
];

export const words = {
  sport: [
    { name: "Soccer" },
    { name: "Basketball" },
    { name: "Baseball" },
    { name: "American Football" },
    { name: "Tennis" },
    { name: "Golf" },
    { name: "Rugby" },
    { name: "Cricket" },
    { name: "Ice Hockey" },
    { name: "Field Hockey" },
    { name: "Volleyball" },
    { name: "Table Tennis" },
    { name: "Badminton" },
    { name: "Swimming" },
    { name: "Track and Field" },
    { name: "Boxing" },
    { name: "Mixed Martial Arts (MMA)" },
    { name: "Wrestling" },
    { name: "Gymnastics" },
    { name: "Cycling" },
    { name: "Skiing" },
    { name: "Snowboarding" },
    { name: "Surfing" },
    { name: "Skateboarding" },
    { name: "Sailing" },
    { name: "Rowing" },
    { name: "Archery" },
    { name: "Fencing" },
    { name: "Equestrian" },
    { name: "Lacrosse" },
    { name: "Handball" },
    { name: "Softball" },
    { name: "Water Polo" },
    { name: "Biathlon" },
    { name: "Triathlon" },
    { name: "Weightlifting" },
    { name: "Powerlifting" },
    { name: "Bodybuilding" },
    { name: "Curling" },
    { name: "Darts" },
    { name: "Bowling" },
    { name: "Snooker" },
    { name: "Horse Racing" },
    { name: "Auto Racing (NASCAR, Formula 1)" },
    { name: "Motocross" },
    { name: "Bobsleigh" },
    { name: "Luge" },
    { name: "Skeleton" },
    { name: "Judo" },
    { name: "Taekwondo" },
    { name: "Manchester United" },
    { name: "Real Madrid" },
    { name: "FC Barcelona" },
    { name: "Bayern Munich" },
    { name: "Liverpool FC" },
    { name: "New England Patriots" },
    { name: "Green Bay Packers" },
    { name: "Los Angeles Lakers" },
    { name: "Golden State Warriors" },
    { name: "Chicago Bulls" },
    { name: "New York Yankees" },
    { name: "Boston Red Sox" },
    { name: "Los Angeles Dodgers" },
    { name: "Toronto Maple Leafs" },
    { name: "Montreal Canadiens" },
    { name: "Chicago Blackhawks" },
    { name: "Mumbai Indians" },
    { name: "Chennai Super Kings" },
    { name: "Sydney Sixers" },
    { name: "Leinster Rugby" },
    { name: "New Zealand All Blacks" },
    { name: "Toulouse" },
    { name: "Paris Saint-Germain" },
    { name: "Juventus" },
    { name: "AC Milan" },
    { name: "San Francisco 49ers" },
    { name: "Dallas Cowboys" },
    { name: "Boston Celtics" },
    { name: "Houston Rockets" },
    { name: "Atlanta Braves" },
    { name: "Philadelphia Flyers" },
    { name: "Pittsburgh Penguins" },
    { name: "Kolkata Knight Riders" },
    { name: "Brisbane Heat" },
    { name: "Bath Rugby" },
    { name: "Saracens" },
    { name: "Atletico Madrid" },
    { name: "Borussia Dortmund" },
    { name: "Inter Milan" },
    { name: "Cleveland Browns" },
    { name: "Miami Dolphins" },
    { name: "Milwaukee Bucks" },
    { name: "Phoenix Suns" },
    { name: "St. Louis Cardinals" },
    { name: "New York Mets" },
    { name: "Edmonton Oilers" },
    { name: "Detroit Red Wings" },
    { name: "Rajasthan Royals" },
    { name: "Delhi Capitals" },
    { name: "Northampton Saints" },
    { name: "Lionel Messi" },
    { name: "Cristiano Ronaldo" },
    { name: "LeBron James" },
    { name: "Michael Jordan" },
    { name: "Serena Williams" },
    { name: "Roger Federer" },
    { name: "Tiger Woods" },
    { name: "Tom Brady" },
    { name: "Usain Bolt" },
    { name: "Muhammad Ali" },
    { name: "Mike Tyson" },
    { name: "Conor McGregor" },
    { name: "Ronda Rousey" },
    { name: "Simone Biles" },
    { name: "Michael Phelps" },
    { name: "Katie Ledecky" },
    { name: "Rafael Nadal" },
    { name: "Novak Djokovic" },
    { name: "Kobe Bryant" },
    { name: "Shaquille O'Neal" },
    { name: "Sachin Tendulkar" },
    { name: "Virat Kohli" },
    { name: "Steve Smith" },
    { name: "Pelé" },
    { name: "Diego Maradona" },
    { name: "Neymar Jr." },
    { name: "David Beckham" },
    { name: "Eliud Kipchoge" },
    { name: "Mo Farah" },
    { name: "Lewis Hamilton" },
    { name: "Ayrton Senna" },
    { name: "Valentino Rossi" },
    { name: "Danica Patrick" },
    { name: "Nadia Comăneci" },
    { name: "Yelena Isinbayeva" },
    { name: "Carl Lewis" },
    { name: "Jesse Owens" },
    { name: "Jackie Joyner-Kersee" },
    { name: "Lance Armstrong" },
    { name: "Chris Froome" },
    { name: "Eddie Hall" },
    { name: "Hafþór Júlíus Björnsson" },
    { name: "Magnus Carlsen" },
    { name: "Garry Kasparov" },
    { name: "John Cena" },
    { name: "Dwayne 'The Rock' Johnson" },
    { name: "Andre Agassi" },
    { name: "Pete Sampras" },
    { name: "Martina Navratilova" },
    { name: "Steffi Graf" },
  ],
  people: [
    { name: "Albert Einstein" },
    { name: "Isaac Newton" },
    { name: "Leonardo da Vinci" },
    { name: "Galileo Galilei" },
    { name: "Charles Darwin" },
    { name: "Marie Curie" },
    { name: "Nikola Tesla" },
    { name: "Thomas Edison" },
    { name: "Stephen Hawking" },
    { name: "Martin Luther King Jr." },
    { name: "Mahatma Gandhi" },
    { name: "Nelson Mandela" },
    { name: "Mother Teresa" },
    { name: "Winston Churchill" },
    { name: "Abraham Lincoln" },
    { name: "George Washington" },
    { name: "Franklin D. Roosevelt" },
    { name: "John F. Kennedy" },
    { name: "Barack Obama" },
    { name: "Donald Trump" },
    { name: "Elon Musk" },
    { name: "Bill Gates" },
    { name: "Steve Jobs" },
    { name: "Mark Zuckerberg" },
    { name: "Jeff Bezos" },
    { name: "Oprah Winfrey" },
    { name: "Walt Disney" },
    { name: "J.K. Rowling" },
    { name: "William Shakespeare" },
    { name: "Jane Austen" },
    { name: "Mark Twain" },
    { name: "Charles Dickens" },
    { name: "Ernest Hemingway" },
    { name: "Agatha Christie" },
    { name: "George Orwell" },
    { name: "J.R.R. Tolkien" },
    { name: "Emily Dickinson" },
    { name: "Homer" },
    { name: "Plato" },
    { name: "Aristotle" },
    { name: "Socrates" },
    { name: "Confucius" },
    { name: "Buddha" },
    { name: "Muhammad" },
    { name: "Jesus Christ" },
    { name: "Mozart" },
    { name: "Beethoven" },
    { name: "Bach" },
    { name: "Freddie Mercury" },
    { name: "Elvis Presley" },
    { name: "Michael Jackson" },
    { name: "The Beatles" },
    { name: "Madonna" },
    { name: "Whitney Houston" },
    { name: "Prince" },
    { name: "Bob Dylan" },
    { name: "Bob Marley" },
    { name: "Frank Sinatra" },
    { name: "Paul McCartney" },
    { name: "John Lennon" },
    { name: "Beyoncé" },
    { name: "Taylor Swift" },
    { name: "Adele" },
    { name: "Lady Gaga" },
    { name: "Rihanna" },
    { name: "Drake" },
    { name: "Eminem" },
    { name: "Kanye West" },
    { name: "Jay-Z" },
    { name: "Kendrick Lamar" },
    { name: "Leonardo DiCaprio" },
    { name: "Brad Pitt" },
    { name: "Tom Hanks" },
    { name: "Meryl Streep" },
    { name: "Angelina Jolie" },
    { name: "Scarlett Johansson" },
    { name: "Robert De Niro" },
    { name: "Al Pacino" },
    { name: "Jack Nicholson" },
    { name: "Morgan Freeman" },
    { name: "Denzel Washington" },
    { name: "Johnny Depp" },
    { name: "Will Smith" },
    { name: "Jennifer Lawrence" },
    { name: "Julia Roberts" },
    { name: "Sandra Bullock" },
    { name: "Emma Watson" },
    { name: "Keanu Reeves" },
    { name: "Chris Hemsworth" },
    { name: "Dwayne Johnson" },
    { name: "Samuel L. Jackson" },
    { name: "Robert Downey Jr." },
    { name: "Tom Cruise" },
    { name: "Harrison Ford" },
    { name: "Sylvester Stallone" },
    { name: "Clint Eastwood" },
    { name: "Arnold Schwarzenegger" },
    { name: "Charlize Theron" },
    { name: "Cate Blanchett" },
    { name: "Nicole Kidman" },
    { name: "George Clooney" },
    { name: "Bruce Willis" },
  ],
};
